### ISSUE TITLE
Running Error

### ISSUE THREAD

**Issue by ShaikhaTheGreen** [UBC-CIC/COVID19-L3-Net#2]
Thank you all for your contribution! 

```
File "C:\ProgramData\Anaconda3\lib\site-packages\PIL\Image.py", line 2891, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './L3netDemoData/LungMasks\\./L3netDemoData/LungMasks\\3_z132.png'
```

I get this error when I try to run the command:
`python trainval.py -e open_source_unet2d -d ./L3netDemoData/ -sb ./checkpoints/ -r 1
`

Although I'm sure, I'm in the right directory..

Please assist.

```
My full error message:
{'batch_size': 1,
 'dataset': {'name': 'open_source', 'transform': 'basic', 'transform_mode': 3},
 'dataset_size': {'train': 'all', 'val': 'all'},
 'lr': 1e-05,
 'max_epoch': 100,
 'model': {'base': 'unet2d',
           'loss': 'dice',
           'name': 'semseg',
           'pretrained': 'checkpoints/unet2d_aio_pre_luna.ckpt'},
 'num_channels': 1,
 'optimizer': 'adam'}
Experiment saved in ./checkpoints/c95406f65039d8dd03e539d5bce5d34a
Starting experiment at epoch 0
Training:   0%|                                                                                                                            | 0/146 [00:00<?, ?it/s]Traceback (most recent call last):
  File "trainval.py", line 182, in <module>
    num_workers=args.num_workers)
  File "trainval.py", line 106, in trainval
    train_dict = model.train_on_loader(train_loader)
  File "C:\Users\User\OneDrive - The Pennsylvania State University\Research-MacBook Pro\Deep Learning\COVID19-L3-Net-master\src\models\semseg.py", line 68, in train_on_loader
    for batch in train_loader:
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 345, in __next__
    data = self._next_data()
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 385, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\User\OneDrive - The Pennsylvania State University\Research-MacBook Pro\Deep Learning\COVID19-L3-Net-master\src\datasets\open_source.py", line 79, in __getitem__
    lung_name)).transpose(Image.FLIP_LEFT_RIGHT))
  File "C:\ProgramData\Anaconda3\lib\site-packages\PIL\Image.py", line 2891, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './L3netDemoData/LungMasks\\./L3netDemoData/LungMasks\\3_z132.png'

```

**Comment by IssamLaradji** [comment]
Was it fixed with this change https://github.com/UBC-CIC/COVID19-L3-Net/pull/4?
